CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL, is_verified INTEGER DEFAULT 0, totp_secret TEXT, twofa_enabled INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE courses (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, slug TEXT UNIQUE, description TEXT, price_cents INTEGER DEFAULT 0, is_paid INTEGER DEFAULT 0);
CREATE TABLE purchases (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, course_id INTEGER, stripe_session_id TEXT, status TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
